In [4]:
import numpy as np
import pandas as pd

**Create a dataframes**

In [5]:
#Creating a dataframe from a dictionary
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#creating a dataform from a datalist
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list)
colunms=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list,columns=colunms)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and indexing of columns**

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#For selecting 1 columns
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [9]:
#For selecting 2 columns
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new columns**

In [20]:
df2['Designation']=['Doctor','Eng.','Eng.','Doctor']

In [21]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000        Eng.
3  Linda   42    London   85000      Doctor

**Remove a column**

In [22]:
#Here if you want to remove the whole columns from the data then you want to use inplace=True
#if you want to remove a row means := df2.drop(1,axis=0,implace=True)
df2.drop('Designation',axis=1,inplace=True)

In [23]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Select Rows**

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
#For selectimg a single row use .loc[]
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [28]:
#for selecting multiple rows
df2.loc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [29]:
#for selecting using index then use .iloc[]
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of rows and columns**

In [34]:
#Far selecting multiple subsets of rows and columns
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [33]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection**

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
# If you give condition as i want to see the people whosw=e age is above 30\
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [38]:
#i want to see the people whose age is above 30 and city is paris
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000