In [1]:
import numpy as np
import pandas as pd

**Merge**

In [2]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

#DataFrame 2: Salary information

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],'Salary': [60000, 80000, 65000, 70000, 90000],'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [3]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [4]:
salaries

   employee_id  Salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [9]:
#Here we merge 2 data sets by using a common column 
#inner means it will take the common only
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  Salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [10]:
#outter means it will take the whole employee _id
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   Salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [14]:
#if you use how='left' means it will merge with the bases on 'on' left side value of on
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   Salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [15]:
#if you use how='right' means it will merge with the bases on 'on' right side value of on
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  Salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**COncatination of 2 DataFrames**

In [33]:
df1= pd.DataFrame({
    'A': ['Α0', 'A1', 'A2'], 
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'] 
})
df2= pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5'] 
})

In [34]:
df1

    A   B   C
0  Α0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [35]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [36]:
pd.concat([df1,df2])

    A   B   C
0  Α0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [37]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  Α0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joning 2 Data Frames**

In [38]:
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index=[1,2,3])
df2=pd.DataFrame({
    'Score':[85,95,70]
},index=[2,3,4])

In [39]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [40]:
df2

   Score
2     85
3     95
4     70

In [44]:
df1.join(df2)

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   95.0

In [43]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   95.0
4      NaN   70.0