In [1]:
import numpy as np
import pandas as pd

**Find missing data**

In [3]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
# isna()will check whether the value is null or not
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
#  any() will check whether the whole column has any null value
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Remove Missing Values**

In [7]:
#It will remove the whole row of having null valur  
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [8]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [11]:
#thresh=n :- here it will select the rows of having n no of non null values 
df.dropna(thresh=2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Filling the non null values**

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
#HEre by using fillna(x) the null values will be replaced with x
#But all this is temperary if you want to change in the main means we want to use implace=True
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [18]:
#To give different values to null values in diffent columns use this one 
values={'A':0,'B':100,'C':300,'D':500}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  300.0  500.0
4  5.0  5  300.0    5.0

In [20]:
#To fill the null value with its mean value
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0